Name: Training_LocaleLanguageMeasurementSystem
Type: ProjectFolder
Children:
- File: UI/UI.yaml
- File: Model/Model.yaml
- File: Converters/Converters.yaml
- File: Alarms/Alarms.yaml
- File: Recipes/Recipes.yaml
- File: Loggers/Loggers.yaml
- File: DataStores/DataStores.yaml
- File: Reports/Reports.yaml
- File: 'OPC-UA/OPC-UA.yaml'
- File: CommDrivers/CommDrivers.yaml
- File: NetLogic/NetLogic.yaml
- File: Security/Security.yaml
- File: Translations/Translations.yaml
- File: Retentivity/Retentivity.yaml
- Name: PasswordPolicy
  Type: PasswordPolicy
  Children:
  - Name: MaximumPasswordAge
    Type: PropertyType
    DataType: UInt16
    Value: 0
  - Name: EnforcePasswordHistory
    Type: PropertyType
    DataType: Byte
    Value: 0
  - Name: MinimumPasswordAge
    Type: PropertyType
    DataType: UInt16
    Value: 0
  - Name: MinimumPasswordLength
    Type: PropertyType
    DataType: Byte
    Value: 0
- Name: Authentication
  Type: PropertyGroup
  Children:
  - Name: DefaultUserFolder
    Type: NodePointer
    DataType: NodeId
    ReferenceType: HasProperty
    Value: {"IdType":2,"Id":"28fa632b2dd4c48ec853386dda4ef3cf","Namespace":16}
    Children:
    - Name: Kind
      Type: PropertyType
      DataType: NodeId
      Value: {"Id":61}
- Name: AlarmConfiguration
  Type: PropertyGroup
  Children:
  - Name: BranchingEnabled
    Type: BaseDataVariableType
    DataType: Boolean
    ReferenceType: HasProperty
    Value: false
- Name: Localization
  Type: PropertyGroup
  Children:
  - Name: Locales
    Type: BaseDataVariableType
    DataType: String
    ReferenceType: HasProperty
    ValueRank: OneDimension
    ArrayDimensions: [0]
    Value: ["en-US","it-IT"]
  - Name: LocaleFallbackList
    Type: BaseDataVariableType
    DataType: String
    ReferenceType: HasProperty
    ValueRank: OneDimension
    ArrayDimensions: [0]
    Value: ["en-US"]
  - Name: MeasurementSystemMap
    Type: BaseDataVariableType
    DataType: MeasurementSystemMapItem
    ReferenceType: HasProperty
    ValueRank: OneDimension
    ArrayDimensions: [0]
    Value: [{"TypeId":{"Id":235,"Namespace":1},"Body":{"From":{"TypeId":{"Id":244,"Namespace":1},"Body":{"Id":12888,"NamespaceIndex":0}},"InternationalSystemOfUnits":{"TypeId":{"Id":244,"Namespace":1},"Body":{"Id":12888,"NamespaceIndex":0}},"USCustomarySystem":{"TypeId":{"Id":244,"Namespace":1},"Body":{"Id":5059895,"NamespaceIndex":0}},"BritishImperialUnits":{"TypeId":{"Id":244,"Namespace":1},"Body":{"Id":5060149,"NamespaceIndex":0}}}}]
